### ISSUE TITLE
`glp_free: memory allocation error` with v4.63

### ISSUE THREAD

**Issue by xkollar** [jyp/glpk-hs#7]
When compiled/run with glpk 4.63 (also .65) I am getting

```
glp_free: memory allocation error
Error detected in file env/alloc.c at line 72
```

(Solver runs, returns value, (event prints solution)) but after some time running program dies, seems with thread that was used to run it?)

Compiled/run against 4.57 it works. There might have been some major changes as debian seem to have changed package name from `libglpk36` to `libglpk40` somewhere between.

Sorry for imprecise/incomplete data, might update when I find some time.

**Comment by tpiraux** [comment]
same problem
